# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-14 10:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default=datetime.datetime(2016, 9, 14, 10, 45, 32, 88715, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
